image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

stages:
  - build

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run build
    - npm run lint
    - npm run coverage
  artifacts:
    paths:
      - ./coverage
    expire_in: 1 week
    when: always
