image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

stages:
  - build

build:
  stage: build
  script:
    - yarn install
    - yarn run lint
    - yarn run build
    - yarn run coverage
    # - yarn run lint # enable once initial issues fixed.
  artifacts:
    paths:
      - ./coverage
    expire_in: 1 week
    when: always
